variables:
  CT_USER: "root"
  PROJECT_NAME: "NginxProxyManagerHelper"
  PROJECT_DIR: "/data/$PROJECT_NAME"
  REMOTE_SERVER: "172.0.0.106"

stages:
  - init
  - deploy

.ssh_prepare: &ssh_prepare
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - ssh-keygen -R $REMOTE_SERVER && ssh-keyscan $REMOTE_SERVER >> ~/.ssh/known_hosts
    - eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa

.ct_prepare: &ct_prepare
    - echo "CT UPDATE && UPGRADE"
    - ssh $CT_USER@$REMOTE_SERVER "sudo apt update && sudo apt -y upgrade && sudo apt autoremove"
    - echo "CT PYTHON3-PIP|VENV INSTALL"
    - ssh $CT_USER@$REMOTE_SERVER "sudo apt -y install python3-pip python3.11-venv"
    - echo "CREATING FOLDER IF NOT EXIST"
    - ssh $CT_USER@$REMOTE_SERVER "mkdir -p $PROJECT_DIR"
    - echo "CREATING VENV ON CT"
    - ssh $CT_USER@$REMOTE_SERVER "test -e $PROJECT_DIR/.venv || /usr/bin/python3 -m venv $PROJECT_DIR/.venv"

.update_script: &update_script
    - echo "COPY LAST VERSION"
    - /usr/bin/sftp $CT_USER@$REMOTE_SERVER:$PROJECT_DIR/ <<< $'put ./*'
    - echo "CHANGING RIGHTS TO 755"
    - ssh $CT_USER@$REMOTE_SERVER "chmod -R 755 $PROJECT_DIR"
    - echo "INSTALLING REQUIREMENTS"
    - ssh $CT_USER@$REMOTE_SERVER "$PROJECT_DIR/.venv/bin/pip install -r $PROJECT_DIR/requirements.txt"

init_job:
  stage: init
  tags:
    - ct_shell
  script:
    - *ssh_prepare
    - *ct_prepare
  allow_failure: false
  needs: []
  when: manual

deploy_job:
  stage: deploy
  tags:
    - ct_shell
  script:
    - *update_script
  allow_failure: false
  needs: []
  when: manual